/**
 * Convex API - Auto-generated file
 * 
 * This file is auto-generated by `npx convex dev`.
 * DO NOT manually edit this file.
 * 
 * If you need mock types for development without Convex,
 * see: src/mocks/convexApi.ts
 * 
 * Run `npx convex dev` in the project root to generate real types.
 */

// This is a placeholder. Run `npx convex dev` to generate real types.
// The actual generated file will replace this content.

export {};
